### ISSUE TITLE
My twelfth first post

### ISSUE THREAD

**Issue by DrHyde** [blogs-perl-org/blogs.perl.org#76]
I've posted to blogs.perl.org 11 times.  And still when I try to post a new article, I get invited to write my first post!

**Comment by benkasminbullock** [comment]
I don't see this at the moment on my account, perhaps the issue was resolved by an update? Since this dates from nearly eleven years ago, if it can't be confirmed it should be closed.

**Comment by DrHyde** [comment]
It still happens. See the screenshot, which has a link "Write your first post" while also saying on the right that I've already written 47 of 'em
![Screenshot 2022-07-07 at 14 11 45](https://user-images.githubusercontent.com/216826/177782116-6e7536d6-306b-4776-9e9d-92d0a6c60708.png)
.

**Comment by ap** [comment]
Silly question, but have you ever dismissed it by clicking the X at the top right (which for whatever reason is not rendering correctly)?

**Comment by ap** [comment]
Silly question, but have you ever dismissed the Welcome box by clicking the X at the top right (which for whatever reason is not rendering correctly)?

**Comment by DrHyde** [comment]
Umm, no, I don't think I had! That has made it go away, at least temporarily!

**Comment by ap** [comment]
Well then 🙂 Based on the way these widgets work, it should be permanent – barring some entirely different bug anyway.

**Comment by ap** [comment]
(That is the `new_user` widget btw, which is added to the dashboard when a blog is created. But it’s just static text – which is why it still says “Write your first post” 12 years and 47 posts… basically expecting that you’ll dismiss it, I guess.)
